### ISSUE TITLE
Unable to add css output directory (PhpStorm 5.0.4)

### ISSUE THREAD

**Issue by intmainreturn0** [acdvorak/intellij-lessc-plugin#16]
Hello.
I have just installed a plugin from here: http://plugins.intellij.net/plugin?pr=&pluginId=7059 (downloaded, then in plugin manager "Install plugin from disk", selected "lib/lessc-plugin.jar", installed successfully).
Then I go to project settings, section "LESS compiler", add new item, select LESS directory. Then I click "+" in block "CSS Output directory", but nothing happens: just no reaction.
"Compile to CSS" in context menu also doesn't work.

**Comment by zergussino** [comment]
Confirming. Followed same installation procedure. Same problem - cannot assign CSS output directories.  

PhpStorm 5.0.2, Build PS-121.322, OpenJDK 1.7.0_09 64-bit, openSUSE 12.2 (x86_64)

**Comment by acdvorak** [comment]
Could you possibly post your IDE log files?  See [Collecting PhpStorm/WebStorm Logs](http://devnet.jetbrains.net/docs/DOC-1202) for instructions.

**Comment by intmainreturn0** [comment]
Hello. During analyzing IDEa.log, I found the following:

2012-11-06 13:12:33,698 [  23973]  ERROR - com.intellij.ide.IdeEventQueue - Error during dispatching of java.awt.event.MouseEvent[MOUSE_RELEASED,(1182,211),absolute(1522,300),button=1,modifiers=Button1,clickCount=1] on dialog0 
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.promptForFilePath(CssConfigurableForm.java:219)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.promptForFilePath(CssConfigurableForm.java:213)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.addRow(CssConfigurableForm.java:178)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.access$300(CssConfigurableForm.java:57)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm$4.run(CssConfigurableForm.java:161)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm$4.run(CssConfigurableForm.java:158)
    at com.intellij.ui.ToolbarDecorator$4.doAdd(ToolbarDecorator.java:415)
    at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:61)
    at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:197)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:171)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:134)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:312)
    at java.awt.Component.processEvent(Component.java:6055)
             .....
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils PluginClassLoader[LESS CSS Compiler, 2.3.3]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 98 more

and

2012-11-06 13:12:33,700 [  23975]  ERROR - com.intellij.ide.IdeEventQueue - Original exception:  
java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils PluginClassLoader[LESS CSS Compiler, 2.3.3]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.promptForFilePath(CssConfigurableForm.java:219)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.promptForFilePath(CssConfigurableForm.java:213)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.addRow(CssConfigurableForm.java:178)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm.access$300(CssConfigurableForm.java:57)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm$4.run(CssConfigurableForm.java:161)
    at net.andydvorak.intellij.lessc.ui.CssConfigurableForm$4.run(CssConfigurableForm.java:158)
    at com.intellij.ui.ToolbarDecorator$4.doAdd(ToolbarDecorator.java:415)
              ....

If this doesn't help, I can post whole log file.

**Comment by acdvorak** [comment]
Wow, I can't believe I didn't catch this earlier:

> selected "lib/lessc-plugin.jar"

You need to choose the `.zip` file after selecting "Install plugin from disk", not the `.jar`.  Don't unzip the archive.

The good news is, it's a super easy fix :-)

I'm going to close this issue.  Please let me know if the problem persists for you and I'll be happy to reopen it.

Thanks!

**Comment by thinkadoo** [comment]
Although I created the folders - http://cl.ly/M6VJ
I still get this message - http://cl.ly/M7CH
PHPStorm Version - http://cl.ly/M6XZ
