### ISSUE TITLE
Doesn't work under IntelliJ 13!

### ISSUE THREAD

**Issue by MuppetGate** [acdvorak/intellij-lessc-plugin#62]
Just installed the plugin under IntelliJ 13 and I cannot set up profiles. The button to open the file browser for the source path doesn't work. This is not hugely serious because you can copy and paste the path into the field. However, the + button for the CSS output folder doesn't work.

And it appears that it's having trouble saving the profile.

**Comment by MuppetGate** [comment]
Okay, I think I know what the problem is: The signature for the chooseFile method seems to have changed. 

Here's the error I'm seeing.

2013-12-09 15:58:37,782 [ 180363]  ERROR - llij.ide.plugins.PluginManager - com.intellij.openapi.fileChooser.FileChooser.chooseFile(Lcom/intellij/openapi/project/Project;Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/openapi/vfs/VirtualFile; 
java.lang.NoSuchMethodError: com.intellij.openapi.fileChooser.FileChooser.chooseFile(Lcom/intellij/openapi/project/Project;Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/openapi/vfs/VirtualFile;
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm.promptForFilePath(LessProfileConfigurableForm.java:234)
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm.promptForFilePath(LessProfileConfigurableForm.java:225)
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm.addRow(LessProfileConfigurableForm.java:190)
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm.access$100(LessProfileConfigurableForm.java:58)
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm$3.run(LessProfileConfigurableForm.java:159)
    at net.andydvorak.intellij.lessc.ui.configurable.LessProfileConfigurableForm$3.run(LessProfileConfigurableForm.java:156)
    at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:407)
    at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:65)
    at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:222)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:170)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:311)

**Comment by bilekt3** [comment]
I am voting in excellent plugin :+1:

**Comment by just-boris** [comment]
+1, have the same error

**Comment by pfilipsson** [comment]
+1, have same error.

**Comment by MuppetGate** [comment]
Hi there. I think I've fixed the problem. You can find the corrected zip file here:

https://github.com/MuppetGate/intellij-lessc-plugin/tree/master/lessc-plugin

**Comment by pfilipsson** [comment]
When running the updated plugin I get:
09:22:40 LESS CSS Compiler Error: blue-bootstrap-template.less: java.lang.NullPointerException

It might have installed it wrong, but I do not have time to look into it further.

**Comment by just-boris** [comment]
@MuppetGate I confirm previous comment. Have the same error message

**Comment by MuppetGate** [comment]
Mmm. Not sure what's going on here. Seems to work fine on mine. If I can get it to break then I should be able to fix it. Could someone post the complete log? Might help if I can find the line where the problem is occurring.

**Comment by MuppetGate** [comment]
If I can't fix it during the holidays then the FileWatcher plugin from IntelliJ is an equally good option.

**Comment by leftovers** [comment]
It seems there is no resouces js files in lessc-plugin.jar inside zip file that downloaded from https://github.com/MuppetGate/intellij-lessc-plugin/tree/master/lessc-plugin

**Comment by MuppetGate** [comment]
Now that is odd....

**Comment by MuppetGate** [comment]
Could someone give this one a try:

http://d.pr/f/VL1a

**Comment by leftovers** [comment]
Tried.
No, It's not working.
Project Setting menu is gone now...
and no compile.

**Comment by MuppetGate** [comment]
Bugger ... :-(

Not sure what's going on then. I've tried it on two fresh machines and it still seems to be fine.  Could be that there's a dependency that's already installed on all my machines.

One last go at a complete rebuild:

http://d.pr/f/hfDj

Then I'd advise moving to IntelliJ's own FileWatcher set up (which is a lot more versatile).

**Comment by leftovers** [comment]
I got "LESS CSS Compiler Error: main.less: java.lang.NullPointerException" again.
Project Setting menu is working.
And now resources gone... :-(

I'll maybe try FileWatcher.
Thank you for your advice ;-)

**Comment by ghost** [comment]
Facing the same problem :(
Will there be a bugfix in the future? :)

However, great work! Thank you :+1: 

Error Log:

2013-12-22 14:44:26,395 [  11827]  ERROR - llij.ide.plugins.PluginManager - com.intellij.openapi.fileChooser.FileChooser.chooseFile(Lcom/intellij/openapi/project/Project;Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/openapi/vfs/VirtualFile; 
java.lang.NoSuchMethodError: com.intellij.openapi.fileChooser.FileChooser.chooseFile(Lcom/intellij/openapi/project/Project;Lcom/intellij/openapi/fileChooser/FileChooserDescriptor;Lcom/intellij/openapi/vfs/VirtualFile;)Lcom/intellij/openapi/vfs/VirtualFile;
    at net.andydvorak.intellij.lessc.ui.configurable.TextFieldWithBrowseButtonImpl$1.actionPerformed(TextFieldWithBrowseButtonImpl.java:54)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:272)
    at java.awt.Component.processMouseEvent(Component.java:6414)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2084)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
    at java.awt.Container.dispatchEventImpl(Container.java:2128)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
    at java.awt.Dialog$1.run(Dialog.java:1049)
    at java.awt.Dialog$3.run(Dialog.java:1101)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Dialog.show(Dialog.java:1099)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:786)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
    at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1543)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1511)
    at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:72)
    at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:54)
    at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:63)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:170)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:311)
    at java.awt.Component.processEvent(Component.java:6179)
    at java.awt.Container.processEvent(Container.java:2084)
    at java.awt.Component.dispatchEventImpl(Component.java:4776)
    at java.awt.Container.dispatchEventImpl(Container.java:2142)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
    at java.awt.Container.dispatchEventImpl(Container.java:2128)
    at java.awt.Window.dispatchEventImpl(Window.java:2492)
    at java.awt.Component.dispatchEvent(Component.java:4604)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:690)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2013-12-22 14:44:26,397 [  11829]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 13.0.1  Build #IU-133.331 
2013-12-22 14:44:26,397 [  11829]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2013-12-22 14:44:26,398 [  11830]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2013-12-22 14:44:26,398 [  11830]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2013-12-22 14:44:26,398 [  11830]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X

**Comment by MuppetGate** [comment]
This looks a lot like you're running the old one. 

Did you download it from here?

http://d.pr/f/hfDj

It seems to work fine on my Mac.

**Comment by ghost** [comment]
No, I'm using the one from the IntelliJ plugin manager.

If I install your plugin from the link you've provided, am I able to use the Plugin-Manager for future updates?

**Comment by MuppetGate** [comment]
You will be able to use the Plug-in manager for future updates if you delete the one that you installed from disk.

I don't want to put it up on the plugin manager because it's not really my code, and it doesn't seem to work for a few people and I'm not sure why. I've just tried a fresh install of IntelliJ 13 and it works perfectly for me on Windows and Mac.

Again, I think folk would be better off with FileWatcher.

**Comment by MuppetGate** [comment]
Might seem like a silly question, but are folk deleting the old plugin before trying to install the new one from the zip file?

**Comment by just-boris** [comment]
I use archive from https://github.com/acdvorak/intellij-lessc-plugin/issues/62#issuecomment-31095940. Now I can open and change plugin's settings but I still can't compile to css, `java.lang.NullPointerException` appearing. Could you provide changes in source code in your fork instead of build version in zip, that I can help to fix it with you?

**Comment by MuppetGate** [comment]
Yup, all the changes should in the fork:

https://github.com/MuppetGate/intellij-lessc-plugin

**Comment by MuppetGate** [comment]
Okay, it looks like a build problem. It could be working on mine because I have nodejs installed on both machines.

**Comment by MuppetGate** [comment]
Riggghttttt...... Okay. Hang on a mo. I think  I haven't told IntelliJ to include the javascript resources.

**Comment by MuppetGate** [comment]
Okay, tenth time's the charm!

http://d.pr/f/nNTS

The missing resources are now included.

Someone care to give this one a try, because everything seems to work okay on mine ....

**Comment by leftovers** [comment]
Yes, it works perfect!

Thank you for your great work ;-)

**Comment by just-boris** [comment]
I confirm, last version is working good, thanks!
Maybe it worth send a pull request to @acdvorak to make this version available through JetBrains repository

**Comment by MuppetGate** [comment]
Okay, thanks for your patience, everyone ... :-)

I've sent a pull request so we'll see what happens.

**Comment by maxio89** [comment]
I've noticed a link to a working version too late, so I've done my own fixes.

https://github.com/maxio89/intellij-lessc-plugin/tree/idea13

Maybe eventually these updates will be included in official repository.

**Comment by acdvorak** [comment]
This issue should be fixed in the official JetBrains plugin repository.

Thanks to @MuppetGate and @maxio89 for submitting fixes (#63 and #65)!
